[package]
name = "rust_library"
version = "0.1.0"
edition = "2021"

[dependencies]
scylla = "0.15"
tokio = { version = "1", features = ["full"] }
uuid = "1.1.2"
thiserror = "1.0"

[lib]
crate-type = ["cdylib"]

